// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Accounting_Business.Persistence.Entities;

public partial class AccountClassification
{
    public int Id { get; set; }

    public string Name { get; set; }

    public bool? IsActive { get; set; }

    public virtual ICollection<Account> AccountAccountClassifications { get; set; } = new List<Account>();

    public virtual ICollection<Account> AccountSubAccountClassifications { get; set; } = new List<Account>();

    public virtual ICollection<SubAccountClassification> SubAccountClassifications { get; set; } = new List<SubAccountClassification>();
}