// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Accounting_Business.Persistence.Entities;

public partial class Account
{
    public int Number { get; set; }

    public string Name { get; set; }

    public string EnglishName { get; set; }

    public int CurrencyId { get; set; }

    public int? ParentAccountNumber { get; set; }

    public int AccountClassificationId { get; set; }

    public int SubAccountClassificationId { get; set; }

    public int? BudgetItem { get; set; }

    public int Level { get; set; }

    public bool IsActive { get; set; }

    public virtual AccountClassification AccountClassification { get; set; }

    public virtual Currency Currency { get; set; }

    public virtual AccountClassification SubAccountClassification { get; set; }
}