// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Accounting_Business.Persistence.Entities;

public partial class AdditionalInformation
{
    public int Id { get; set; }

    public int ProfileId { get; set; }

    public string Name { get; set; }

    public virtual Profile Profile { get; set; }
}