// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Accounting_Business.Persistence.Entities;

public partial class Currency
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string IsoCode { get; set; }

    public int? DecimalPlaces { get; set; }

    public virtual ICollection<Account> Accounts { get; set; } = new List<Account>();

    public virtual ICollection<Profile> Profiles { get; set; } = new List<Profile>();
}