// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Accounting_Business.Persistence.Entities;

public partial class Employee
{
    public int Id { get; set; }

    public string EmployeeCode { get; set; }

    public string Name { get; set; }

    public int ClassificationId { get; set; }

    public string IdentificationNumber { get; set; }

    public string Address { get; set; }

    public int? CityId { get; set; }

    public string FirstPhoneNumber { get; set; }

    public string SecondPhoneNumber { get; set; }

    public DateOnly? BirthDate { get; set; }

    public DateOnly? HiringDate { get; set; }

    public DateOnly? EndOfServiceDate { get; set; }

    public int? MaritalStatusId { get; set; }

    public int? GenderId { get; set; }

    public double? CreditLimit { get; set; }

    public int? NumberOfChildren { get; set; }

    public string EmployeeImagePath { get; set; }

    public virtual City City { get; set; }

    public virtual AccountClassification Classification { get; set; }

    public virtual Gender Gender { get; set; }

    public virtual MaritalStatus MaritalStatus { get; set; }
}