// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Accounting_Business.Persistence.Entities;

public partial class ExchangeCurrency
{
    public int Id { get; set; }

    public int CurrencyId { get; set; }

    public int BaseCurrencyId { get; set; }

    public decimal BuyPrice { get; set; }

    public decimal SellPrice { get; set; }

    public DateOnly EffectiveDate { get; set; }

    public virtual Currency BaseCurrency { get; set; }

    public virtual Currency Currency { get; set; }
}