// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Accounting_Business.Persistence.Entities;

public partial class JournalVoucherCheck
{
    public int Id { get; set; }

    public int VoucherId { get; set; }

    public int AccountId { get; set; }

    public string AccountName { get; set; }

    public string SubAccount { get; set; }

    public decimal DebitAmount { get; set; }

    public decimal CreditAmount { get; set; }

    public string Description { get; set; }

    public virtual Account Account { get; set; }

    public virtual JournalVoucher Voucher { get; set; }
}