// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Accounting_Business.Persistence.Entities;

public partial class JournalVoucher
{
    public int Id { get; set; }

    public DateOnly VoucherDate { get; set; }

    public TimeOnly VoucherTime { get; set; }

    public int CurrencyId { get; set; }

    public decimal ExchangeRate { get; set; }

    public DateOnly TaxDueDate { get; set; }

    public decimal TaxPercentage { get; set; }

    public string ReferenceNumber { get; set; }

    public int AgentId { get; set; }

    public virtual ICollection<JournalVoucherCheck> JournalVoucherChecks { get; set; } = new List<JournalVoucherCheck>();
}