// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Accounting_Business.Persistence.Entities;

public partial class ProfileSubAccount
{
    public int Id { get; set; }

    public string ProfileCode { get; set; }

    public string Name { get; set; }

    public virtual Profile ProfileCodeNavigation { get; set; }
}