// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Accounting_Business.Persistence.Entities;

public partial class Profile
{
    public string ProfileCode { get; set; }

    public string Name { get; set; }

    public string EnglishName { get; set; }

    public string IdentificationNumber { get; set; }

    public int ClassificationId { get; set; }

    public int? CurrencyId { get; set; }

    public string Address { get; set; }

    public int? CityId { get; set; }

    public int? PhoneNumber { get; set; }

    public int? MobileNumber { get; set; }

    public int? Fax { get; set; }

    public int? PriceCategory { get; set; }

    public double? Discount { get; set; }

    public double? CreditLimit { get; set; }

    public int? AgentId { get; set; }

    public string Email { get; set; }

    public string Description { get; set; }

    public bool? IsActive { get; set; }

    public virtual ICollection<AdditionalInformation> AdditionalInformations { get; set; } = new List<AdditionalInformation>();

    public virtual Agent Agent { get; set; }

    public virtual City City { get; set; }

    public virtual ProfileClassfication Classification { get; set; }

    public virtual Currency Currency { get; set; }

    public virtual PriceCategory PriceCategoryNavigation { get; set; }

    public virtual ICollection<ProfileSubAccount> ProfileSubAccounts { get; set; } = new List<ProfileSubAccount>();
}