// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Accounting_Business.Persistence.Entities;

public partial class SubAccountClassification
{
    public int Id { get; set; }

    public string Name { get; set; }

    public bool? IsActive { get; set; }

    public int AccountClassificationId { get; set; }

    public virtual AccountClassification AccountClassification { get; set; }

    public virtual ICollection<Account> Accounts { get; set; } = new List<Account>();
}