// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Accounting_Business.Persistence.Entities;

public partial class VoucherCheck
{
    public int Id { get; set; }

    public int VoucherId { get; set; }

    public int CheckNo { get; set; }

    public int BankId { get; set; }

    public int AccountId { get; set; }

    public DateOnly DueDate { get; set; }

    public decimal Amount { get; set; }

    public virtual Voucher Voucher { get; set; }
}