// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Accounting_Business.Persistence.Entities;

public partial class Voucher
{
    public int Id { get; set; }

    public DateOnly VoucherDate { get; set; }

    public TimeOnly TimeCreated { get; set; }

    public int CurrencyId { get; set; }

    public decimal ExchangeRate { get; set; }

    public decimal AmountPayment { get; set; }

    public decimal CashAmountPayment { get; set; }

    public decimal CheckAmountPayment { get; set; }

    public int CashAccountTo { get; set; }

    public int CheckAccountTo { get; set; }

    public int AccountFrom { get; set; }

    public string AccountFromName { get; set; }

    public int AgentId { get; set; }

    public string SubAccount { get; set; }

    public string ReferenceNumber { get; set; }

    public decimal Discount { get; set; }

    public string Description { get; set; }

    public decimal TotalAmount { get; set; }

    public int VoucherTypeId { get; set; }

    public virtual ICollection<VoucherCheck> VoucherChecks { get; set; } = new List<VoucherCheck>();
}